ALTER TABLE `User`
  ADD COLUMN `role` VARCHAR(191) NOT NULL DEFAULT 'user',
  ADD COLUMN `plan` VARCHAR(191) NOT NULL DEFAULT 'Básico',
  ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'active',
  ADD COLUMN `devices` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `lastLogin` DATETIME(3) NULL,
  ADD COLUMN `avatarUrl` VARCHAR(191) NULL;
